version: 2
jobs:
  build:
    docker:
      - image: circleci/node:15

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v0-dependencies-{{ checksum "package-lock.json" }}
          - v0-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v0-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: build
          command: npm run build
